### ISSUE TITLE
Smooth Exit

### ISSUE THREAD

**Issue by grant** [GoogleCloudPlatform/functions-framework-nodejs#143]
The FF should smoothly exit, even with a process interrupt. This would create a better developer experience.

This is what a user sees when we CTRL-C:

```sh
Serving function...
Function: function
URL: http://localhost:8080/
^CReceived SIGINT
Error: Process exited with code 0
    at process.<anonymous> (<folder>/node_modules/@google-cloud/functions-framework/build/src/invoker.js:396:29)
    at process.emit (events.js:203:13)
    at process.EventEmitter.emit (domain.js:471:20)
    at process.exit (internal/process/per_thread.js:158:15)
    at Server.<anonymous> (<folder>/node_modules/@google-cloud/functions-framework/build/src/invoker.js:402:29)
    at Object.onceWrapper (events.js:291:20)
    at Server.emit (events.js:203:13)
    at Server.EventEmitter.emit (domain.js:471:20)
    at emitCloseNT (net.js:1572:8)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
```

Source:

```ts
process.on('exit', code => {
  logAndSendError(new Error(`Process exited with code ${code}`), latestRes);
});
```

We're not really doing any good by logging the stacktrace of the Node process, maybe a one-liner error would be better.

**Comment by grant** [comment]
Confirmed, this is still an issue today.

`    "@google-cloud/functions-framework": "^1.6.0"`

**Comment by grant** [comment]
This should be fixed now on `master` with https://github.com/GoogleCloudPlatform/functions-framework-nodejs/pull/187.

@hdp617 maybe cut a minor version? We might want to cut a major version after the CE fix.
