### ISSUE TITLE
Deployment mechanism changed? Can no longer deploy

### ISSUE THREAD

**Issue by mikquinlan** [GoogleCloudPlatform/functions-framework-nodejs#154]
Hi there

Until yesterday I was able to deploy my config and functions using the following three steps:

`firebase functions:config:set analytics.mx1=value1  analytics.mx2=value2 -P dev`

`firebase deploy --only functions:analytics_downloadMerchants,functions:analytics_deleteReceipt,functions:analytics_processReceipt,functions:analytics_downloadTransactions,functions:analytics_syncTransactionsForUser --token $FIREBASE_TOKEN -P dev`

`gcloud functions deploy analytics_downloadTransactions --vpc-connector=default-connector --ingress-settings=all --egress-settings=all --region=us-central1 --project=project-name`

I have not changed the deployment mechanism and it is executed via our Gitlab pipeline. 

Today the first two firebase commands succeed.

The third `gcloud functions deploy` does not with the following error in the logs:

```
Provided module can't be loaded.
       analytics_downloadTransactions                2020-06-30 15:30:46.668  Is there a syntax error in your code?
       analytics_downloadTransactions                2020-06-30 15:30:46.668  Detailed stack trace: TypeError: Cannot read property 'mx1' of undefined
       analytics_downloadTransactions                2020-06-30 15:30:46.668      at Object.<anonymous> (/workspace/transactions/index.js:17:39)
       analytics_downloadTransactions                2020-06-30 15:30:46.668      at Module._compile (internal/modules/cjs/loader.js:778:30)
       analytics_downloadTransactions                2020-06-30 15:30:46.668      at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
       analytics_downloadTransactions                2020-06-30 15:30:46.668      at Module.load (internal/modules/cjs/loader.js:653:32)
       analytics_downloadTransactions                2020-06-30 15:30:46.668      at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
       analytics_downloadTransactions                2020-06-30 15:30:46.668      at Function.Module._load (internal/modules/cjs/loader.js:585:3)
       analytics_downloadTransactions                2020-06-30 15:30:46.668      at Module.require (internal/modules/cjs/loader.js:692:17)
       analytics_downloadTransactions                2020-06-30 15:30:46.668      at require (internal/modules/cjs/helpers.js:25:18)
       analytics_downloadTransactions                2020-06-30 15:30:46.668      at Object.<anonymous> (/workspace/index.js:8:79)
       analytics_downloadTransactions                2020-06-30 15:30:46.668      at Module._compile (internal/modules/cjs/loader.js:778:30)
```

So I used the `--set-env-vars` variable to fix this issue and I now get this error when executing the above `gcloud functions update` command:

```
Could not load the function, shutting down.
E      analytics_downloadTransactions                2020-06-30 15:30:48.176  Error: function terminated. Recommended action: inspect logs for termination reason. Function cannot be initialized.
       analytics_downloadTransactions                2020-06-30 15:34:53.027  Warning, FIREBASE_CONFIG and GCLOUD_PROJECT environment variables are missing. Initializing firebase-admin will fail
       analytics_downloadTransactions                2020-06-30 15:34:53.029  Provided module can't be loaded.
       analytics_downloadTransactions                2020-06-30 15:34:53.029  Is there a syntax error in your code?
```

I am using the same gcloud SDK (294.0.0). 

Has anything happened changed in the GCP functions environment?

Thanks

**Comment by mikquinlan** [comment]
Addressed [here](https://github.com/firebase/firebase-tools/issues/2413)
