### ISSUE TITLE
Support nested modules (multiple package.json files)

### ISSUE THREAD

**Issue by anniefu** [GoogleCloudPlatform/functions-framework-nodejs#202]
Hello,

I have a project setup where the top-level folder module is a functions-framework function with a `package.json` and it takes a dependency on a nested folder module that has its own `package.json`.

Pretty similar to the setup described here: https://stackoverflow.com/questions/31773546/the-best-way-to-run-npm-install-for-nested-folders.

Unfortunately, none of the workarounds there for supporting nested package.json files work with functions-framework. I get this error:
```
Provided module can't be loaded.
Did you list all required modules in the package.json dependencies?
Detailed stack trace: Error: Cannot find module 'queue-fifo'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/local/google/home/anniefu/go/src/gke-internal.googlesource.com/platinum/cli/pkg/typescript/runtime/build/src/user/fn.js:4:13)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
Could not load the function, shutting down.
```

top-level `package.json` dependencies:
```
  "dependencies": {
    "@google-cloud/functions-framework": "^1.7.1",
    "@types/body-parser": "^1.19.0",
    "body-parser": "^1.19.0",
    "express": "^4.17.1",
    "user": "file:src/user"
  },
```

nested `src/user/package.json` dependencies:
```
  "dependencies": {
    "queue-fifo": "^0.2.6"
  },
```

**Comment by hdp617** [comment]
Could you provide reproducible steps? Is there a `node_modules` in the nested folder `src/user`?

**Comment by grant** [comment]
I'm not sure what the exact issue is either.
Can you provide steps to reproduce the problem and provide the expected and actual output of a command?
