### ISSUE TITLE
callback() does not work in local environment

### ISSUE THREAD

**Issue by scarolan** [GoogleCloudPlatform/functions-framework-nodejs#243]
I am testing a function that is meant to be run via background triggers.  Below is the text of my function which now works fine on Google Cloud Functions, but fails when run locally via functions-framework.  If instead I use `req` and `res` as function arguments the script works locally.

```
async function pollenCount(data, context, callback) {
  let { browser, page } = await openConnection();

  try {
    await page.goto(allergyurl, { waitUntil: "load" });
    const pollenData = await page.evaluate(
      () =>
        document.querySelector(
          // Selector for scraped text
          "#main > div > div > div:nth-child(1) > div.grid__content.grid__content_full-width_false > div.grid__main.grid__main_sticky_right.grid__main_full-width_false > div > div:nth-child(1) > div > article > div.article__body > div:nth-child(1) > p"
        ).innerText
    );

    // JSON stringify the output of our transformData function
    output = JSON.stringify(await transformData(pollenData));

    // Console log output should now match what is returned in the browser
    console.log(output);

    // Write JSON data to GCS file in our bucket
    const Readable = require("stream").Readable;
    Readable.from(output).pipe(file.createWriteStream());

    // Finally send the JSON data to the browser or requestor
    //res.status(200).send(output);
    callback(null, output);
  } catch (err) {
    //res.status(500).send(err.message);
    callback(new Error('Failed'));
  } finally {
    await closeConnection(page, browser);
  }
}
```

**Comment by scarolan** [comment]
The error message:

```
Unhandled rejection
TypeError: callback is not a function
    at pollenCount (C:\Users\sean\git_repos\pollencount\index.js:115:5)
Error: Process exited with code 16
    at process.<anonymous> (C:\Users\sean\git_repos\pollencount\node_modules\@google-cloud\functions-framework\build\src\invoker.js:275:22)
    at process.emit (events.js:315:20)
    at process.EventEmitter.emit (domain.js:467:12)
    at process.exit (internal/process/per_thread.js:169:15)
    at Object.sendCrashResponse (C:\Users\sean\git_repos\pollencount\node_modules\@google-cloud\functions-framework\build\src\logger.js:37:9)
    at process.<anonymous> (C:\Users\sean\git_repos\pollencount\node_modules\@google-cloud\functions-framework\build\src\invoker.js:271:22)
    at process.emit (events.js:315:20)
    at process.EventEmitter.emit (domain.js:467:12)
    at processPromiseRejections (internal/process/promises.js:245:33)
    at processTicksAndRejections (internal/process/task_queues.js:94:32)
```

**Comment by grant** [comment]
I don't think you can use an async functions here. Are you using the correct signature type of event?

I require more details to reproduce the issue.

**Comment by scarolan** [comment]
If async functions are not supported for local testing, let's go ahead and close this issue.
