### ISSUE TITLE
Is Yarn 2 supported?

### ISSUE THREAD

**Issue by ehannes** [GoogleCloudPlatform/functions-framework-nodejs#318]
Hi!

Does the Node.js runtime supports Yarn 2? I have a cloud function. I first installed all packages with Yarn 1 and deployed it. Then I wanted to upgrade to Yarn 2. When I then try to deploy, I get the following error message in the function log:
```
2021-08-26 21:02:42.052 CESTCloud FunctionsUpdateFunctioneurope-west1:my_functionhannes@my-email.com {@type: type.googleapis.com/google.cloud.audit.AuditLog, authenticationInfo: {…}, authorizationInfo: […], methodName: google.cloud.functions.v1.CloudFunctionsService.UpdateFunction, request: {…}, requestMetadata: {…}, resourceLocation: {…}, resourceName: projects/my-project/locations/europe-west…
2021-08-26 21:03:38.562 CESTmy_function Provided module can't be loaded.
2021-08-26 21:03:38.562 CESTmy_function Did you list all required modules in the package.json dependencies?
2021-08-26 21:03:38.562 CESTmy_function Detailed stack trace: Error: Cannot find module 'node-fetch'
2021-08-26 21:03:38.562 CESTmy_function Require stack:
2021-08-26 21:03:38.562 CESTmy_function - /workspace/src/lib/API/some_api.js
2021-08-26 21:03:38.562 CESTmy_function - /workspace/src/lib/my_function.js
2021-08-26 21:03:38.562 CESTmy_function - /workspace/src/index.js
2021-08-26 21:03:38.562 CESTmy_function - /layers/google.nodejs.functions-framework/functions-framework/node_modules/@google-cloud/functions-framework/build/src/loader.js
2021-08-26 21:03:38.562 CESTmy_function - /layers/google.nodejs.functions-framework/functions-framework/node_modules/@google-cloud/functions-framework/build/src/index.js
2021-08-26 21:03:38.562 CESTmy_function at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
2021-08-26 21:03:38.562 CESTmy_function at Function.Module._load (internal/modules/cjs/loader.js:746:27)
2021-08-26 21:03:38.562 CESTmy_function at Module.require (internal/modules/cjs/loader.js:974:19)
2021-08-26 21:03:38.562 CESTmy_function at require (internal/modules/cjs/helpers.js:92:18)
2021-08-26 21:03:38.562 CESTmy_function at Object.<anonymous> (/workspace/src/lib/API/some_api.js:36:15)
2021-08-26 21:03:38.562 CESTmy_function at Module._compile (internal/modules/cjs/loader.js:1085:14)
2021-08-26 21:03:38.562 CESTmy_function at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
2021-08-26 21:03:38.562 CESTmy_function at Module.load (internal/modules/cjs/loader.js:950:32)
2021-08-26 21:03:38.562 CESTmy_function at Function.Module._load (internal/modules/cjs/loader.js:790:14)
2021-08-26 21:03:38.562 CESTmy_function at Module.require (internal/modules/cjs/loader.js:974:19)
2021-08-26 21:03:38.563 CESTmy_function Could not load the function, shutting down.}
```

This is our deploy command:
```
$ gcloud functions deploy my_function --entry-point my_function --runtime nodejs14 --trigger-http --region europe-west1 --env-vars-file=env.yaml
```

And this is how the `dependencies` looks like in `package.json`:
```
  "dependencies": {
    "fetch-cookie": "^0.11.0",
    "node-fetch": "^2.6.1"
  },
```

I have just verified that reverting back to Yarn 1 solved the problem.

**Comment by grant** [comment]
Hey @ehannes,

We currently use yarn `1.22.5` right now. I don't think we've added any special support for yarn 2. Here's the code:

https://github.com/GoogleCloudPlatform/buildpacks/blob/a552888ec958e7443d6c715ebad2f5b6261b920a/cmd/nodejs/yarn/main.go#L117

I am not familiar with what yarn 2 requires. It looks like we must set `yarn set version berry` in this case? Anything else? How would we detect that a user wants to use yarn 2 vs 1?

Can you describe a bit more how we'd install dependencies with yarn 2?

**Comment by matthewrobertson** [comment]
Hi @ehannes, this sounds like a feature request for our [buildpacks project](https://github.com/GoogleCloudPlatform/buildpacks). I will close this issue and replace it with one in that repository.
